---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest

    container:
      image: elementary/docker:odin-unstable

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update
        apt install -y intltool libclutter-gst-3.0-dev libclutter-gtk-1.0-dev libgranite-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgtk-3-dev meson valac

    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  Flatpak:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6-${{ matrix.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU for aarch64 emulation
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: videos.flatpak
          manifest-path: io.elementary.videos.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.arch }}

  Lint:
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: io.elementary.vala-lint -d .
