name: CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:juno-unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y clutter-gst-3.0-dev -y clutter-gtk-1.0-dev -y libgranite-dev -y libgstreamer-plugins-base1.0-dev
        apt install -y libgstreamer1.0-dev -y libgtk-3-dev -y meson -y valac

    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:

    runs-on: ubuntu-latest

    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@master
      with:
        bundle: "io.elementary.videos.flatpak"
        manifest-path: "io.elementary.videos.yml"
        repository-name: "elementary"
        repository-url: "https://flatpak.elementary.io/elementary.flatpakrepo"
        cache-key: "flatpak-builder-${{ github.sha }}"

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
